project:
  type: website
  output-dir: docs

website:
  title: "My Awesome Introductory Machine Learning Blog"

  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/trongdle
      - icon: linkedin
        href: https://www.linkedin.com/in/duc-trong-le-5a2654224/

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





